### ISSUE TITLE
Implement shape point packing, using delta compression

### ISSUE THREAD

**Issue by laurentg** [mecatran/gtfsvtor#42]
Implement the same type of packing that #31 for shape points.

Pack delta/delta² int coordinates using some sort of variable-length encoding. Most of the deltas are indeed rather small, and their int representation may fit in fewer bits than the default 32.

**Comment by laurentg** [comment]
@hbruch This is implemented, you may want to test with your data. But the memory savings are way less impressive than with stop times (around 5 to 10 bytes per shape point).

**Comment by hbruch** [comment]
@laurentg This change led only to minor speed and memory improvements. I attach the results of two consecutive runs below. The first with -Xmx4G took 151s, the second -Xm3G failed with an OoM Exception. I used amazoncorretto:11. In case you want to reproduce, you could download a weekly updated, slightly improved (agency_urls added) copy of the DELFI feed [here](https://gtfs.mfdz.de/DELFI.gtfs.zip). 

```
GTFSVTOR version dev
Copyright (c) 2020 Mecatran
This program comes with absolutely no warranty.
This is free software, and you are welcome to redistribute it
under certain conditions; see the license file for details.

8200000 shape points   Packed 8278509 points, 222182 shapes (1735k) in (42533k)
Total 44269k. Avg bytes: 5.48 per shape point, 204.03 per shape
Loaded 39499835 stop times in 67870ms
Packed 39499835 stop times, 2053641 trips (48132k) in 283167 time patterns (6515k), 230979 stop patterns (11411k)
Total 66059k. Avg bytes: 1.71 per stop time, 32.94 per trip, 23.56 per time pattern, 50.59 per stop pattern
Loaded './20200605_fahrplaene_gesamtdeutschland_gtfs.zip' in 91657ms. Used memory: ~1256Mb
Indexed 56189 calendars in 3829ms
Spatial-indexed 563908 stops in 258ms
Linear-indexed 224935 shape.patterns in 21716ms
Report output to validation-results.html
Validation done in 151820 ms: 13427 INFO, 511797 WARNING, 513021 ERROR, 0 CRITICAL
```
Second run, using -Xmx3G:
```
GTFSVTOR version dev
Copyright (c) 2020 Mecatran
This program comes with absolutely no warranty.
This is free software, and you are welcome to redistribute it
under certain conditions; see the license file for details.

8200000 shape points   Packed 8278509 points, 222182 shapes (1735k) in (42533k)
Total 44269k. Avg bytes: 5.48 per shape point, 204.03 per shape
Loaded 39499835 stop times in 84161ms
Packed 39499835 stop times, 2053641 trips (48132k) in 283167 time patterns (6515k), 230979 stop patterns (11411k)
Total 66059k. Avg bytes: 1.71 per stop time, 32.94 per trip, 23.56 per time pattern, 50.59 per stop pattern
Loaded './20200605_fahrplaene_gesamtdeutschland_gtfs.zip' in 106302ms. Used memory: ~1256Mb
Indexed 56189 calendars in 4223ms
Spatial-indexed 563908 stops in 245ms
Linear-indexed 224935 shape.patterns in 21319ms
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.StringUTF16.compress(StringUTF16.java:160)
	at java.base/java.lang.String.<init>(String.java:3214)
	at java.base/java.lang.String.<init>(String.java:276)
	at com.univocity.parsers.common.input.AbstractCharInputReader.getString(AbstractCharInputReader.java:492)
	at com.univocity.parsers.csv.CsvParser.parseSingleDelimiterRecord(CsvParser.java:185)
	at com.univocity.parsers.csv.CsvParser.parseRecord(CsvParser.java:108)
	at com.univocity.parsers.common.AbstractParser.parseNext(AbstractParser.java:574)
	at com.mecatran.gtfsvtor.loader.impl.UnivocityCsvDataTable$1.hasNext(UnivocityCsvDataTable.java:113)
	at com.mecatran.gtfsvtor.loader.impl.SourceInfoDataReloader.lambda$loadSourceInfos$2(SourceInfoDataReloader.java:74)
	at com.mecatran.gtfsvtor.loader.impl.SourceInfoDataReloader$$Lambda$175/0x00000008000b5c40.accept(Unknown Source)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.mecatran.gtfsvtor.loader.impl.SourceInfoDataReloader.loadSourceInfos(SourceInfoDataReloader.java:53)
	at com.mecatran.gtfsvtor.lib.GtfsVtor.validate(GtfsVtor.java:98)
	at com.mecatran.gtfsvtor.cmdline.GtfsVtorMain.main(GtfsVtorMain.java:56)
```

**Comment by laurentg** [comment]
Thanks for this report!

As a side note: currently Gtfsvtor will reload the source info in a second stage, in order to generate the HTML report, once the validation has been done and all issues have been created (source info is the raw CSV entire row for entities related to issues). This can lead to lot of memory being used (here you have lots of errors and warnings). Having the CSV data in the report is useful but not necessary, especially if we output a JSON report one day. I'll create an issue to add an option to better control that.
